name: Tests (Windows)

# Windows 전용 테스트 - Excel/HWP 자동화 기능이 Windows에서만 완전 지원됨
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.13']

    env:
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: 1

    steps:
    - name: Configure PowerShell UTF-8 encoding
      shell: pwsh
      run: |
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        [Console]::InputEncoding = [System.Text.Encoding]::UTF8
        $OutputEncoding = [System.Text.Encoding]::UTF8
        echo "PowerShell UTF-8 encoding configured"
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "requirements.txt"

    - name: Install dependencies
      run: |
        uv venv
        uv pip install -r requirements.txt

    - name: Install package in development mode
      run: |
        uv pip install -e .

    - name: Test CLI installation and basic commands
      run: |
        echo "Testing CLI installation and basic commands..."
        uv run oa --version
        uv run oa info --format json || echo "Expected: Excel/HWP not available in CI"
        uv run oa excel list --format json
        uv run oa install-guide --format json
        echo "Testing help commands (UTF-8 encoding test)..."
        uv run oa excel workbook-create --help
        uv run oa excel workbook-open --help
        uv run oa excel range-read --help
        uv run oa excel chart-add --help
        echo "All CLI tests completed successfully!"

    - name: Test version system
      run: |
        uv run python -c "from pyhub_office_automation.version import get_version_info; import json; print(json.dumps(get_version_info(), indent=2))"

  lint:
    runs-on: windows-latest

    env:
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: 1

    steps:
    - name: Configure PowerShell UTF-8 encoding
      shell: pwsh
      run: |
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        [Console]::InputEncoding = [System.Text.Encoding]::UTF8
        $OutputEncoding = [System.Text.Encoding]::UTF8
        echo "PowerShell UTF-8 encoding configured"
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Install dependencies
      run: |
        uv venv
        uv pip install flake8 black isort

    - name: Check code formatting with black
      run: |
        uv run black --check pyhub_office_automation/

    - name: Check import sorting with isort
      run: |
        uv run isort --check-only pyhub_office_automation/

    - name: Lint with flake8
      run: |
        uv run flake8 pyhub_office_automation/ --count --select=E9,F63,F7,F82 --show-source --statistics
        uv run flake8 pyhub_office_automation/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics